# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 11 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: AAAAAAAAA
google_analytics: AAAAAAAAAAAAAAA
title: 围观的白菜哥哥

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 没事fork的博客

description: Stylish Jekyll Theme
author:
  name: 围观的白菜哥哥
  email: 616625682@qq.com
  github: ZhangAiQiang
  twitter: 
  pinterest: 没有
  linkedin: 没有
  bio: You are every single day.
  email_md5: AB97D9FB02E91A577854F15F49FE7000

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
